# Generated by Django 2.2.6 on 2019-10-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaItemEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evento.Evento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.Item')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='lista_produtos',
            field=models.ManyToManyField(through='Evento.ListaItemEvento', to='Item.Item'),
        ),
    ]
